// Generated by CoffeeScript 1.6.3
(function() {
  var fibrous;

  fibrous = require('use-global-fibrous');

  exports.setup = function(context) {
    return process.versions.fibrous = fibrous.version;
  };

  exports.postStart = function(context) {
    var rawEval, repl;
    repl = context.repl;
    rawEval = repl["eval"];
    return repl["eval"] = fibrous(function(input, context, filename) {
      return rawEval.sync(input, context, filename);
    });
  };

}).call(this);
