// Generated by CoffeeScript 1.6.3
(function() {
  var fibrous;

  fibrous = require('use-global-fibrous');

  exports.setup = function(context) {
    var nesh;
    nesh = context.nesh;
    process.versions.fibrous = fibrous.version;
    nesh.defaults.prompt = "fibrous-" + nesh.defaults.prompt;
    nesh.defaults.welcome = nesh.defaults.welcome.replace("\n", " with fibrous " + fibrous.version + "\n", 1);
    return nesh.log.debug("Using fibrous " + fibrous.version + " from " + (require.resolve('fibrous')));
  };

  exports.postStart = function(context) {
    var rawEval, repl;
    repl = context.repl;
    rawEval = repl["eval"];
    repl["eval"] = fibrous(function(input, context, filename) {
      return rawEval.sync(input, context, filename);
    });
    return repl.context.fibrous = fibrous;
  };

}).call(this);
